CREATE TABLE `com_customer` (
                                `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '企业id',
                                `company_code` varchar(50) DEFAULT NULL COMMENT '企业编码',
                                `company_name` varchar(255) DEFAULT NULL COMMENT '企业名称',
                                `company_status` tinyint(2) DEFAULT NULL COMMENT '状态 1 正常 2 停用',
                                `mobile` varchar(255) DEFAULT NULL COMMENT '客户联系人号码',
                                `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
                                `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
                                `is_deleted` int(1) DEFAULT '0' COMMENT '是否删除',
                                `kefu_id` bigint(20) DEFAULT NULL COMMENT '客服id',
                                `kefu_name` varchar(255) DEFAULT NULL COMMENT '客服姓名',
                                `kefu_mobile` varchar(255) DEFAULT NULL COMMENT '客服手机号码',
                                `kefu_email` varchar(255) DEFAULT NULL COMMENT '联系邮箱',
                                `city_id` bigint(20) DEFAULT NULL COMMENT '城市id',
                                `city_name` varchar(255) DEFAULT NULL COMMENT '城市名称',
                                `province_id` bigint(20) DEFAULT NULL COMMENT '省份id',
                                `province_name` varchar(255) DEFAULT NULL COMMENT '省份名称',
                                `industry` int(11) DEFAULT NULL COMMENT '产业',
                                `service_rate` decimal(10,5) DEFAULT NULL COMMENT '服务费率',
                                `sales_id` bigint(20) DEFAULT NULL COMMENT '对接销售id（来自大管家）',
                                `sales_name` varchar(50) DEFAULT NULL COMMENT '销售姓名',
                                `sales_mobile` varchar(30) DEFAULT NULL COMMENT '销售手机',
                                `sales_email` varchar(50) DEFAULT NULL COMMENT '销售邮箱',
                                `address` varchar(255) DEFAULT NULL COMMENT '公司地址',
                                `telephone` varchar(50) DEFAULT NULL COMMENT '公司电话',
                                `bank_name` varchar(100) DEFAULT NULL COMMENT '开户行',
                                `bank_no` varchar(50) DEFAULT NULL COMMENT '银行账户',
                                `account_no` varchar(50) DEFAULT NULL COMMENT '账户',
                                `receive_address` varchar(255) DEFAULT NULL COMMENT '收件地址',
                                `receive_city_id` bigint(20) DEFAULT NULL COMMENT '收件城市id',
                                `receive_name` varchar(255) DEFAULT NULL COMMENT '收件人名',
                                `receive_province_id` bigint(20) DEFAULT NULL COMMENT '收件省份id',
                                `receive_telephone` varchar(255) DEFAULT NULL COMMENT '收件电话',
                                `receive_city_name` varchar(255) DEFAULT NULL COMMENT '收件城市名',
                                `receive_province_name` varchar(255) DEFAULT NULL COMMENT '收件身份名',
                                `remark` varchar(1024) DEFAULT '' COMMENT '备注信息',
                                `channel_id` bigint(20) DEFAULT NULL COMMENT '渠道id',
                                `channel_code` varchar(50) DEFAULT NULL COMMENT '渠道code',
                                `classification` varchar(50) DEFAULT NULL COMMENT '企业分类',
                                `org_code` varchar(255) DEFAULT NULL COMMENT '组织机构代码',
                                `reg_address` varchar(255) DEFAULT NULL COMMENT '注册地址',
                                `enterprise_type` varchar(50) DEFAULT NULL COMMENT '企业类型',
                                `reg_capital` varchar(150) DEFAULT NULL COMMENT '注册资本',
                                `establis_date` datetime DEFAULT NULL COMMENT '成立日期',
                                `legal_representative` varchar(50) DEFAULT NULL COMMENT '法人代表',
                                `reg_authority` varchar(255) DEFAULT NULL COMMENT '登记机关',
                                `business_scope` varchar(2000) DEFAULT NULL COMMENT '经营范围',
                                `industry_type` varchar(50) DEFAULT NULL COMMENT '行业类型',
                                `close_date` datetime DEFAULT NULL COMMENT '关停企业日期',
                                `close_reason` varchar(128) DEFAULT NULL COMMENT '关停原因',
                                PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2163 DEFAULT CHARSET=utf8 COMMENT='客户基本信息表';




CREATE TABLE `com_order` (
                              `id` int(11) NOT NULL COMMENT '订单id',
                              `order_code` varchar(255) DEFAULT NULL COMMENT '订单编码',
                              `amount` double DEFAULT NULL COMMENT '订单金额',
                              `order_type` varchar(255) DEFAULT NULL COMMENT '订单类型',
                              `order_type_name` varchar(255) DEFAULT NULL COMMENT '订单类型名称',
                              `order_start_name` varchar(255) DEFAULT NULL COMMENT '订单开始时间',
                              `order_end_name` varchar(255) DEFAULT NULL COMMENT '订单结束时间',
                              `customer_id` varchar(255) DEFAULT NULL COMMENT '客户id',
                              `customer_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
                              `staff_id` int(11) DEFAULT NULL COMMENT '员工id',
                              `staff_name` varchar(255) DEFAULT NULL COMMENT '员工姓名',
                              `status` varchar(255) DEFAULT NULL COMMENT '订单状态',
                              `channel_id` int(11) DEFAULT NULL COMMENT '渠道id',
                              `channel_code` varchar(100) DEFAULT NULL COMMENT '渠道代码',
                              `parent_channel_id` int(11) DEFAULT NULL COMMENT '上级渠道id',
                              `channel_name` varchar(100) DEFAULT NULL COMMENT '渠道名称',
                              `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                              `create_by` varchar(255) DEFAULT NULL COMMENT '创建人',
                              `update_date` datetime DEFAULT NULL COMMENT '修改时间',
                              `update_by` datetime DEFAULT NULL COMMENT '修改人',
                              `is_deleted` varchar(255) DEFAULT NULL COMMENT '删除标识',
                              PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';
