CREATE TABLE `com_contacts` (
                                `contacts_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '联系人ID',
                                `user_id` bigint(20) DEFAULT NULL COMMENT '用户ID',
                                `dept_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
                                `dept_name` varchar(200) DEFAULT '' COMMENT '部门名称',
                                `post_id` bigint(20) DEFAULT NULL COMMENT '岗位ID',
                                `post_code` varchar(64) DEFAULT NULL COMMENT '岗位编码',
                                `post_name` varchar(200) DEFAULT NULL COMMENT '岗位名称',
                                `login_name` varchar(30) DEFAULT NULL COMMENT '登录账号',
                                `user_name` varchar(200) DEFAULT '' COMMENT '联系人名称',
                                `email` varchar(50) DEFAULT '' COMMENT '用户邮箱',
                                `phonenumber` varchar(11) DEFAULT '' COMMENT '手机号码',
                                `sex` char(1) DEFAULT '0' COMMENT '用户性别（0男 1女 2未知）',
                                `status` char(1) DEFAULT '0' COMMENT '帐号状态（0正常 1停用）',
                                `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
                                `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
                                `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
                                `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                PRIMARY KEY (`contacts_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通讯录';



CREATE TABLE `com_order` (
                             `id` int(11) NOT NULL COMMENT '订单id',
                             `order_code` varchar(64) DEFAULT NULL COMMENT '订单编码',
                             `amount` double DEFAULT NULL COMMENT '订单金额',
                             `post_fee` double DEFAULT NULL COMMENT '邮费',
                             `payment` double DEFAULT NULL COMMENT '实付金额',
                             `order_type` varchar(10) DEFAULT NULL COMMENT '订单类型',
                             `order_type_name` varchar(255) DEFAULT NULL COMMENT '订单类型名称',
                             `order_start_name` datetime DEFAULT NULL COMMENT '订单开始时间',
                             `order_end_name` datetime DEFAULT NULL COMMENT '订单结束时间',
                             `customer_id` varchar(255) DEFAULT NULL COMMENT '客户id',
                             `customer_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
                             `company_user_name` varchar(64) DEFAULT NULL COMMENT '客户联系人名称',
                             `company_title` varchar(64) DEFAULT NULL COMMENT '客户职务',
                             `mobile` varchar(64) DEFAULT NULL COMMENT '客户联系人电话',
                             payment_type varchar(10) DEFAULT null COMMENT '支付方式:1借记卡,2信用卡,3微信,4支付宝,5现金',
                             `status` varchar(10) DEFAULT NULL COMMENT '订单状态:1未付款,2已付款,3已发货,4已签收',
                             `staff_id` int(11) DEFAULT NULL COMMENT '员工id',
                             `staff_name` varchar(255) DEFAULT NULL COMMENT '员工姓名',
                             `channel_id` int(11) DEFAULT NULL COMMENT '渠道id',
                             `channel_code` varchar(100) DEFAULT NULL COMMENT '渠道代码',
                             `parent_channel_id` int(11) DEFAULT NULL COMMENT '上级渠道id',
                             `channel_name` varchar(100) DEFAULT NULL COMMENT '渠道名称',
                             `product_id` int(11) DEFAULT NULL COMMENT '产品id',
                             `product_code` varchar(64) DEFAULT NULL COMMENT '产品编码',
                             `product_name` varchar(64) DEFAULT NULL COMMENT '产品名称',
                             `payment_code` varchar(64) DEFAULT NULL COMMENT '支付流水号',
                             `is_invoice_flag` varchar(64) DEFAULT NULL COMMENT '是否开发票',
                             `invoice_no` varchar(64) DEFAULT NULL COMMENT '发票号',
                             `invoice_amount` varchar(64) DEFAULT NULL COMMENT '发票金额',
                             `is_post_flag` varchar(64) DEFAULT NULL COMMENT '是否快递',
                             `post_no` varchar(64) DEFAULT NULL COMMENT '快递号',
                             `post_start_date` datetime DEFAULT NULL COMMENT '快递开始时间',
                             `post_end_date` datetime DEFAULT NULL COMMENT '快递结束时间',
                             `post_status` datetime DEFAULT NULL COMMENT '快递完成状态',
                             `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                             `create_by` varchar(255) DEFAULT NULL COMMENT '创建人',
                             `update_date` datetime DEFAULT NULL COMMENT '修改时间',
                             `update_by` datetime DEFAULT NULL COMMENT '修改人',
                             `is_deleted` varchar(255) DEFAULT NULL COMMENT '删除标识',
                             `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                             PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';




CREATE TABLE `com_customer` (
                                `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '客户id',
                                `company_code` varchar(64) DEFAULT NULL COMMENT '客户编码',
                                `company_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
                                `company_status` tinyint(2) DEFAULT NULL COMMENT '状态',
                                `company_user_name` varchar(255) DEFAULT NULL COMMENT '客户联系人名称',
                                `company_title` varchar(255) DEFAULT NULL COMMENT '客户职务',
                                `mobile` varchar(64) DEFAULT NULL COMMENT '客户联系人电话',
                                `telephone` varchar(50) DEFAULT NULL COMMENT '客户联系人手机',
                                `address` varchar(255) DEFAULT NULL COMMENT '公司地址',
                                `bank_name` varchar(100) DEFAULT NULL COMMENT '开户行',
                                `bank_no` varchar(50) DEFAULT NULL COMMENT '银行账户',
                                `account_no` varchar(50) DEFAULT NULL COMMENT '账户',
                                `city_id` bigint(20) DEFAULT NULL COMMENT '城市id',
                                `city_name` varchar(255) DEFAULT NULL COMMENT '城市名称',
                                `province_id` bigint(20) DEFAULT NULL COMMENT '省份id',
                                `province_name` varchar(255) DEFAULT NULL COMMENT '省份名称',
                                `industry` int(11) DEFAULT NULL COMMENT '产业',
                                `kefu_id` bigint(20) DEFAULT NULL COMMENT '客服id',
                                `kefu_name` varchar(255) DEFAULT NULL COMMENT '客服姓名',
                                `kefu_mobile` varchar(255) DEFAULT NULL COMMENT '客服手机号码',
                                `kefu_email` varchar(255) DEFAULT NULL COMMENT '联系邮箱',
                                `sales_id` bigint(20) DEFAULT NULL COMMENT '对接销售id',
                                `sales_name` varchar(50) DEFAULT NULL COMMENT '销售姓名',
                                `sales_mobile` varchar(30) DEFAULT NULL COMMENT '销售手机',
                                `sales_email` varchar(50) DEFAULT NULL COMMENT '销售邮箱',
                                `receive_address` varchar(255) DEFAULT NULL COMMENT '收件地址',
                                `receive_city_id` bigint(20) DEFAULT NULL COMMENT '收件城市id',
                                `receive_name` varchar(255) DEFAULT NULL COMMENT '收件人名',
                                `receive_province_id` bigint(20) DEFAULT NULL COMMENT '收件省份id',
                                `receive_telephone` varchar(255) DEFAULT NULL COMMENT '收件电话',
                                `receive_city_name` varchar(255) DEFAULT NULL COMMENT '收件城市名',
                                `receive_province_name` varchar(255) DEFAULT NULL COMMENT '收件身份名',
                                `remark` varchar(1024) DEFAULT '' COMMENT '备注信息',
                                `channel_id` bigint(20) DEFAULT NULL COMMENT '渠道id',
                                `channel_code` varchar(50) DEFAULT NULL COMMENT '渠道code',
                                `classification` varchar(50) DEFAULT NULL COMMENT '企业分类',
                                `reg_address` varchar(255) DEFAULT NULL COMMENT '注册地址',
                                `enterprise_type` varchar(50) DEFAULT NULL COMMENT '企业类型',
                                `reg_capital` varchar(150) DEFAULT NULL COMMENT '注册资本',
                                `establis_date` datetime DEFAULT NULL COMMENT '成立日期',
                                `legal_representative` varchar(50) DEFAULT NULL COMMENT '法人代表',
                                `reg_authority` varchar(255) DEFAULT NULL COMMENT '登记机关',
                                `business_scope` varchar(2000) DEFAULT NULL COMMENT '经营范围',
                                `industry_type` varchar(50) DEFAULT NULL COMMENT '行业类型',
                                `close_date` datetime DEFAULT NULL COMMENT '关停企业日期',
                                `close_reason` varchar(128) DEFAULT NULL COMMENT '关停原因',
                                `company_contract_id` varchar(255) DEFAULT NULL COMMENT '合同id',
                                `company_contract_code` varchar(64) DEFAULT NULL COMMENT '客户合同号',
                                `contract_start_date` datetime DEFAULT NULL COMMENT '合同开始时间',
                                `contract_end_date` datetime DEFAULT NULL COMMENT '合同结束时间',
                                `contract_amount` double DEFAULT NULL COMMENT '合同金额',
                                `contract_total_amount` double DEFAULT NULL COMMENT '累计金流',
                                `contract_is_continue` varchar(2) DEFAULT NULL COMMENT '是否续签客户',
                                `invoice_name` varchar(255) DEFAULT NULL COMMENT '发票名称',
                                `invoice_no` int(11) DEFAULT NULL COMMENT '纳税人识别号',
                                `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
                                `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
                                `is_deleted` int(1) DEFAULT '0' COMMENT '是否删除',
                                PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2164 DEFAULT CHARSET=utf8 COMMENT='客户表';